language: node_js
sudo: false
node_js:
  - 8
script:
  npm test
branches:
  only:
  - master
before_install:
  - export CHROME_BIN=chromium-browser

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
